### ISSUE TITLE
Escape `

### ISSUE THREAD

**Issue by smhmd** [donatj/CsvToMarkdownTable#12] opened 2020-01-05 02:26 UTC
Trying from something like this:
```
`a, à
`e, è
`i, ì
`o, ò
`u, ù
`A, À
`E, È
`I, Ì
`O, Ò
`U, Ù
```

Is it doable? Github cannot seem to escape it.

**Comment by donatj** [comment] 2020-01-05 23:14
```
|    |    | 
|----|----| 
| `a |  à | 
| `e |  è | 
| `i |  ì | 
| `o |  ò | 
| `u |  ù | 
| `A |  À | 
| `E |  È | 
| `I |  Ì | 
| `O |  Ò | 
| `U |  Ù | 
```

**Comment by donatj** [comment] 2020-04-01 22:00
Closing. Cannot reproduce. No reply.

If you can provide any more details I'd happily re-open the ticket.

**Closed by donatj** 2020-04-01 22:00 UTC
